<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { AlertTriangle, Archive, Bot, BrainCircuit, Check, CheckCircle2, ChevronDown, ChevronRight, Clock3, Code2, Download, FileCode2, FolderTree, GitBranch, KeyRound, LoaderCircle, Play, RefreshCcw, Rocket, Server, ShieldCheck, Sparkles, Square, Terminal, TestTube2, Wrench, XCircle, Zap } from 'lucide-vue-next'
import { api, type AgentBuildFile, type AgentBuildRecord, type DeploymentRuntimeStatus, type LLMBuildStatus } from '../api/client'
import { useAppStore } from '../stores/app'
import PageTitle from '../components/PageTitle.vue'
import StatusBadge from '../components/StatusBadge.vue'

const route=useRoute();const app=useAppStore();const projectId=String(route.params.id)
const status=ref<LLMBuildStatus|null>(null);const deployRuntime=ref<DeploymentRuntimeStatus|null>(null);const autoDeploy=ref(false);const deploying=ref(false);const builds=ref<AgentBuildRecord[]>([]);const current=ref<AgentBuildRecord|null>(null);const requirement=ref('构建一个员工培训管理系统：HR 可以创建课程并设置讲师、时间和人数上限；员工可以浏览课程、报名和取消报名；HR 可查看报名名单与培训完成率。需要角色权限、表单校验、REST API、响应式页面和自动化测试。');const buildMode=ref<'initial'|'incremental'>('initial');const maxFixAttempts=ref(2);const starting=ref(false);const instruction=ref('');const sendingInstruction=ref(false);const detailTab=ref('logs');const files=ref<AgentBuildFile[]>([]);const selectedFile=ref<AgentBuildFile|null>(null);const loadingFile=ref(false);let timer:number|undefined
const isRunning=computed(()=>current.value&&['pending','running'].includes(current.value.status))
const isWaitingApproval=computed(()=>current.value?.status==='waiting_approval')
const latestCompleted=computed(()=>builds.value.find(build=>build.status==='completed'))
const stages=computed(()=>[
  {key:'planning',label:'架构规划',agent:'AR',icon:BrainCircuit,progress:10},
  {key:'backend',label:'后端生成',agent:'BE',icon:Server,progress:30},
  {key:'frontend',label:'前端生成',agent:'FE',icon:Code2,progress:50},
  {key:'testing',label:'自动测试',agent:'QA',icon:TestTube2,progress:70},
  {key:'completed',label:'产物打包',agent:'PM',icon:Archive,progress:95},
])
function stageState(stage:{key:string;progress:number}){if(!current.value)return'pending';if(current.value.status==='completed')return'done';if(current.value.status==='failed'&&current.value.currentStage===stage.key)return'failed';if(current.value.currentStage===stage.key||(current.value.currentStage==='fixing'&&stage.key==='testing'))return'active';return current.value.progress>stage.progress?'done':'pending'}
async function load(){try{const [provider,runtime,history]=await Promise.all([api.agentBuildStatus(),api.deploymentRuntimeStatus(),api.agentBuilds(projectId)]);status.value=provider;deployRuntime.value=runtime;builds.value=history;if(history.length){current.value=await api.agentBuild(projectId,history[0].id);if(current.value.status==='completed')await loadFiles()}}catch(error){app.toast('加载失败',error instanceof Error?error.message:'无法读取 Agent 构建状态')}}
async function refresh(){if(!current.value)return;try{current.value=await api.agentBuild(projectId,current.value.id);const idx=builds.value.findIndex(b=>b.id===current.value?.id);if(idx>=0)builds.value[idx]=current.value;if(current.value.status==='completed'&&!files.value.length)await loadFiles()}catch{/* keep current view */}}
async function start(){if(!status.value?.configured){app.toast('模型尚未配置','请在 backend/.env 配置 LLM_BASE_URL、LLM_API_KEY 和 LLM_MODEL。');return}starting.value=true;try{const build=await api.createAgentBuild(projectId,{requirement:requirement.value,template:'fullstack',mode:buildMode.value,baseBuildId:buildMode.value==='incremental'?latestCompleted.value?.id:undefined,autoDeploy:autoDeploy.value&&Boolean(deployRuntime.value?.ready),deployEnvironment:'test',model:status.value.model,maxFixAttempts:maxFixAttempts.value});current.value=build;builds.value.unshift(build);files.value=[];detailTab.value='logs';app.toast('真实 Agent 已启动','架构、后端、前端与测试 Agent 将依次执行。')}catch(error){app.toast('启动失败',error instanceof Error?error.message:'请稍后重试')}finally{starting.value=false}}
async function sendInstruction(){if(!current.value||!instruction.value.trim())return;sendingInstruction.value=true;try{await api.instructAgentBuild(projectId,current.value.id,instruction.value.trim());instruction.value='';await refresh();app.toast('指令已加入 Agent 上下文','将在当前模型调用完成后的下一个安全阶段消费。')}catch(error){app.toast('发送失败',error instanceof Error?error.message:'请稍后重试')}finally{sendingInstruction.value=false}}
async function decideHitl(decision:'approve'|'reject'){if(!current.value)return;try{current.value=await api.decideBuildHitl(projectId,current.value.id,decision,decision==='reject'?'Rejected by project reviewer':'');app.toast(decision==='approve'?'审批已通过':'审批已拒绝','DeepAgents 将从持久 Checkpoint 恢复执行。')}catch(error){app.toast('审批失败',error instanceof Error?error.message:'请稍后重试')}}
async function cancel(){if(!current.value)return;try{current.value=await api.cancelAgentBuild(projectId,current.value.id);app.toast('取消请求已提交','Agent 将在当前安全阶段完成后停止。')}catch(error){app.toast('取消失败',error instanceof Error?error.message:'请稍后重试')}}
async function deployCurrent(){if(!current.value||current.value.status!=='completed')return;if(!deployRuntime.value?.ready){app.toast('Docker 不可用','请启动 Docker daemon 后重试。');return}deploying.value=true;try{const deployment=await api.createApplicationDeployment(projectId,current.value.id,'test');app.toast('部署已启动',`正在构建应用镜像，Deployment ${deployment.id.slice(-8)}。`)}catch(error){app.toast('部署失败',error instanceof Error?error.message:'请稍后重试')}finally{deploying.value=false}}
async function retry(){if(!current.value)return;try{const next=await api.retryAgentBuild(projectId,current.value.id);current.value=next;builds.value.unshift(next);files.value=[];detailTab.value='logs';app.toast('重新构建已启动','将保留原始需求并重新执行全部质量门禁。')}catch(error){app.toast('重试失败',error instanceof Error?error.message:'请稍后重试')}}
async function chooseBuild(build:AgentBuildRecord){current.value=await api.agentBuild(projectId,build.id);files.value=[];selectedFile.value=null;if(current.value.status==='completed')await loadFiles()}
async function loadFiles(){if(!current.value)return;files.value=await api.agentBuildFiles(projectId,current.value.id);if(files.value.length&&!selectedFile.value)await openFile(files.value[0])}
async function openFile(file:AgentBuildFile){if(!current.value)return;loadingFile.value=true;try{selectedFile.value=await api.agentBuildFile(projectId,current.value.id,file.path)}finally{loadingFile.value=false}}
function formatTime(value:string|null){return value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—'}
function logTime(value:string){return new Date(value).toLocaleTimeString('zh-CN',{hour12:false})}
onMounted(async()=>{await load();timer=window.setInterval(()=>{if(isRunning.value)refresh()},1800)})
onUnmounted(()=>timer&&clearInterval(timer))
</script>

<template><div class="content-width agent-build-page"><PageTitle eyebrow="REAL AGENT EXECUTION" title="AI 全栈构建" description="调用真实模型完成架构规划、Vue + FastAPI 代码生成、自动测试与失败修复。"><button class="button secondary" @click="load"><RefreshCcw :size="16"/>刷新</button><button v-if="current?.status==='completed'" class="button secondary" :disabled="deploying||!deployRuntime?.ready" @click="deployCurrent"><LoaderCircle v-if="deploying" :size="15" class="spin"/><Rocket v-else :size="15"/>部署应用</button><a v-if="current?.status==='completed'" class="button primary" :href="api.agentBuildDownloadUrl(projectId,current.id)"><Download :size="16"/>下载源码 ZIP</a></PageTitle>
<section v-if="status&&!status.configured" class="llm-config-banner"><span><KeyRound :size="21"/></span><div><h3>配置模型网关后即可运行真实 Agent</h3><p>当前不会使用 Mock 结果。请将密钥写入后端本地环境文件，前端和 API 均不会回显密钥。</p><code>LLM_BASE_URL=https://your-gateway/v1　 LLM_API_KEY=***　 LLM_MODEL={{status.model}}</code></div><StatusBadge status="paused" label="未配置"/></section>
<section v-else-if="status" class="llm-ready-banner"><span><Sparkles :size="20"/></span><div><small>OPENAI-COMPATIBLE GATEWAY</small><h3>{{status.model}}</h3><p>{{status.baseUrl}}</p></div><span class="gateway-online"><i></i>已配置，可真实执行</span></section>
<div class="agent-build-layout"><main><section class="panel build-request-card"><header class="panel-title"><div><h3>构建需求</h3><p>Agent 将基于项目记忆和已加载 Skills 生成完整应用</p></div><span class="real-agent-chip"><Zap :size="13"/>REAL LLM</span></header><div class="build-request-body"><div class="build-mode-switch"><button :class="{active:buildMode==='initial'}" :disabled="Boolean(isRunning)" @click="buildMode='initial'"><Rocket :size="14"/><span><b>全新构建</b><small>从标准脚手架生成完整应用</small></span></button><button :class="{active:buildMode==='incremental'}" :disabled="Boolean(isRunning)||!latestCompleted" @click="buildMode='incremental'"><GitBranch :size="14"/><span><b>增量修改</b><small>{{latestCompleted?`基于 ${latestCompleted.id.slice(-8)} 最小化变更`:'需要一个已完成构建'}}</small></span></button></div><textarea v-model="requirement" :disabled="Boolean(isRunning)" maxlength="20000"></textarea><div><span>{{requirement.length}} / 20,000</span><label>自动修复次数 <button>{{maxFixAttempts}} 次<ChevronDown :size="13"/></button></label><label class="build-auto-deploy" :class="{disabled:!deployRuntime?.ready}"><input type="checkbox" v-model="autoDeploy" :disabled="!deployRuntime?.ready"/><span><Check :size="11"/></span>通过后自动部署</label><button v-if="!isRunning" class="button primary" :disabled="starting||requirement.length<20||!status?.configured||(buildMode==='incremental'&&!latestCompleted)" @click="start"><LoaderCircle v-if="starting" :size="16" class="spin"/><Rocket v-else :size="16"/>{{starting?'正在创建…':'启动真实 Agent 构建'}}</button><button v-else class="button danger-ghost" @click="cancel"><Square :size="14"/>取消构建</button></div></div></section>
<section v-if="current" class="panel live-build-card"><header><div><span class="live-build-icon" :class="current.status"><Bot :size="22"/><i v-if="isRunning"></i></span><div><div><StatusBadge :status="current.status==='running'?'executing':current.status"/><span>{{current.model}}</span><span>{{current.mode==='incremental'?'增量修改':'全新构建'}}</span><span>Build {{current.id.slice(-8)}}</span></div><h2>{{current.status==='completed'?'全栈应用已生成并通过测试':current.status==='failed'?'构建失败，等待处理':'Agent 团队正在执行'}}</h2><p>{{current.status==='failed'?current.errorMessage:(current.logs.at(-1)?.message||'正在准备 Agent 运行时…')}}</p></div></div><div class="build-progress-ring"><strong>{{current.progress}}<small>%</small></strong></div></header><div class="agent-build-stages"><template v-for="(stage,i) in stages" :key="stage.key"><div :class="stageState(stage)"><span><Check v-if="stageState(stage)==='done'" :size="14"/><XCircle v-else-if="stageState(stage)==='failed'" :size="14"/><component v-else :is="stage.icon" :size="15"/></span><p><b>{{stage.label}}</b><small>{{stage.agent}} Agent</small></p></div><i v-if="i<stages.length-1" :class="{done:stageState(stage)==='done'}"></i></template></div><div class="build-progress-track"><i :style="{width:`${current.progress}%`}"></i></div><footer><span><Clock3 :size="13"/>开始：{{formatTime(current.startedAt)}}</span><span><Wrench :size="13"/>修复轮次：{{current.attempt}} / {{current.maxFixAttempts}}</span><span><Zap :size="13"/>Tokens：{{(current.promptTokens+current.completionTokens).toLocaleString()}}</span><span v-if="current.coverage!==null"><ShieldCheck :size="13"/>覆盖率：{{current.coverage}}%</span><span v-if="current.mode==='incremental'"><GitBranch :size="13"/>改动：{{current.changedFilesCount}} 文件</span><button v-if="current.status==='failed'||current.status==='cancelled'" class="button secondary" @click="retry"><RefreshCcw :size="14"/>重新构建</button></footer></section>
<section v-if="current&&isWaitingApproval" class="panel hitl-approval-card"><span><ShieldCheck :size="20"/></span><div><b>DeepAgents 请求人工审批</b><p>敏感数据库迁移或生产部署已在工具调用前暂停，状态保存在 LangGraph Checkpoint。</p><pre>{{JSON.stringify(current.plan?._meta?.hitlInterrupt||{},null,2)}}</pre></div><button class="button danger-ghost" @click="decideHitl('reject')">拒绝</button><button class="button primary" @click="decideHitl('approve')"><Check :size="14"/>批准并恢复</button></section>
<section v-if="current&&isRunning" class="panel build-intervention-bar"><span><Bot :size="17"/></span><div><b>实时干预 Agent</b><p>指令将在当前模型调用结束后的安全阶段注入后续 Agent 上下文。</p></div><textarea v-model="instruction" placeholder="例如：保持现有 API 兼容，补充空数据边界测试…" @keydown.meta.enter="sendInstruction"></textarea><button class="button primary" :disabled="!instruction.trim()||sendingInstruction" @click="sendInstruction"><LoaderCircle v-if="sendingInstruction" :size="14" class="spin"/><Sparkles v-else :size="14"/>发送指令</button></section>
<section v-if="current" class="panel build-detail-card"><div class="build-detail-tabs"><button :class="{active:detailTab==='logs'}" @click="detailTab='logs'"><Terminal :size="15"/>实时日志 <span>{{current.logs.length}}</span></button><button :class="{active:detailTab==='plan'}" @click="detailTab='plan'"><BrainCircuit :size="15"/>架构计划</button><button :class="{active:detailTab==='tests'}" @click="detailTab='tests'"><TestTube2 :size="15"/>质量门禁 <span>{{current.testResults.length}}</span></button><button :class="{active:detailTab==='files'}" @click="detailTab='files';loadFiles()"><FolderTree :size="15"/>生成文件 <span>{{current.generatedFiles.length||files.length}}</span></button></div>
<div v-if="detailTab==='logs'" class="build-log-view"><div v-for="log in current.logs" :key="log.id" :class="`build-log-${log.level}`"><time>{{logTime(log.createdAt)}}</time><span>{{log.agentKey||'system'}}</span><em>{{log.stage}}</em><p>{{log.message}}</p></div><div v-if="isRunning" class="build-log-wait"><i></i><i></i><i></i></div></div>
<div v-else-if="detailTab==='plan'" class="build-plan-view"><template v-if="Object.keys(current.plan).length"><header><div><small>应用名称</small><strong>{{current.plan.app_name}}</strong></div><div><small>API 接口</small><strong>{{current.plan.api_endpoints?.length||0}}</strong></div><div><small>页面</small><strong>{{current.plan.pages?.length||0}}</strong></div><div><small>验收标准</small><strong>{{current.plan.acceptance_criteria?.length||0}}</strong></div></header><section><h3>方案摘要</h3><p>{{current.plan.summary}}</p></section><div class="plan-columns"><section><h3>API 设计</h3><article v-for="endpoint in current.plan.api_endpoints" :key="endpoint.method+endpoint.path"><span :class="String(endpoint.method).toLowerCase()">{{endpoint.method}}</span><code>{{endpoint.path}}</code><p>{{endpoint.purpose}}</p></article></section><section><h3>页面规划</h3><article v-for="page in current.plan.pages" :key="typeof page==='string'?page:page.name"><FileCode2 :size="15"/><p>{{typeof page==='string'?page:(page.name||page.path)}}</p></article></section></div></template><div v-else class="build-empty"><BrainCircuit :size="27"/><h3>架构 Agent 尚未输出计划</h3><p>进入 planning 阶段后会显示结构化方案。</p></div></div>
<div v-else-if="detailTab==='tests'" class="quality-gates"><article v-for="gate in current.testResults" :key="`${gate.attempt}-${gate.name}`" :class="{passed:gate.passed,failed:!gate.passed}"><span><CheckCircle2 v-if="gate.passed" :size="18"/><XCircle v-else :size="18"/></span><div><h3>{{gate.name}}</h3><p>{{gate.command.join(' ')}}</p><small>第 {{gate.attempt+1}} 轮 · {{gate.elapsedMs}} ms · Exit {{gate.exitCode??'—'}}<b v-if="gate.coverage!==undefined"> · 覆盖率 {{gate.coverage}}%</b></small></div><StatusBadge :status="gate.passed?'completed':'failed'" :label="gate.passed?'通过':'失败'"/></article><div v-if="!current.testResults.length" class="build-empty"><TestTube2 :size="27"/><h3>等待进入测试阶段</h3><p>将依次运行 pytest、npm install 和 Vite production build。</p></div></div>
<div v-else class="generated-files-view"><aside><button v-for="file in files" :key="file.path" :class="{active:selectedFile?.path===file.path}" @click="openFile(file)"><FileCode2 :size="14"/><div><b>{{file.path.split('/').pop()}}</b><small>{{file.path}}</small></div><span>{{file.size}} B</span></button></aside><main><header><code>{{selectedFile?.path||'选择文件'}}</code><span v-if="loadingFile"><LoaderCircle :size="14" class="spin"/>加载中</span></header><pre>{{selectedFile?.content||''}}</pre></main></div></section></main>
<aside class="build-history-column"><section class="panel"><header><h3>构建历史</h3><span>{{builds.length}}</span></header><button v-for="build in builds" :key="build.id" :class="{active:current?.id===build.id}" @click="chooseBuild(build)"><span class="history-build-icon" :class="build.status"><Rocket :size="15"/></span><div><b>{{build.id.slice(-8)}}</b><small>{{formatTime(build.createdAt)}}</small><p>{{build.requirement.slice(0,42)}}…</p></div><StatusBadge :status="build.status==='running'?'executing':build.status" :label="`${build.progress}%`"/></button><div v-if="!builds.length" class="history-empty"><Rocket :size="22"/><p>还没有真实 Agent 构建记录</p></div></section><section class="panel build-security-card"><ShieldCheck :size="18"/><div><b>真实执行安全边界</b><p>模型仅返回结构化文件，路径经过校验；pytest 与 npm build 使用资源受限的项目工作区执行。</p></div></section></aside></div></div></template>
