<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { AlertTriangle, BrainCircuit, Check, CheckCircle2, ChevronDown, Clock3, Code2, Cpu, Database, HardDrive, LoaderCircle, MemoryStick, MessageCircle, Play, Plus, RefreshCcw, Search, Server, ShieldCheck, Sparkles, Terminal, Trash2, Wrench, X, Zap } from 'lucide-vue-next'
import { api, type AgentContextRecord, type MemoryRecord, type SandboxRunRecord, type SandboxStatus, type SkillRecord } from '../api/client'
import { useAppStore } from '../stores/app'
import PageTitle from '../components/PageTitle.vue'
import StatusBadge from '../components/StatusBadge.vue'
import ConversationPanel from '../components/ConversationPanel.vue'

const route=useRoute();const app=useAppStore();const projectId=String(route.params.id);const tab=ref('memory');const loading=ref(true);const memories=ref<MemoryRecord[]>([]);const skills=ref<SkillRecord[]>([]);const runs=ref<SandboxRunRecord[]>([]);const sandbox=ref<SandboxStatus|null>(null);const showAdd=ref(false);const executing=ref(false);const resultRun=ref<SandboxRunRecord|null>(null);const search=ref('');const agentFilter=ref('');const contextAgent=ref('project-manager');const contextQuery=ref('导出功能与回归测试');const context=ref<AgentContextRecord|null>(null)
const memoryForm=ref({agentKey:'project-manager',scope:'project',memoryType:'semantic',key:'',content:'',importance:.7,tags:''})
const code=ref(`import json
from datetime import datetime

result = {
    "sandbox": "ready",
    "message": "Hello from isolated Python",
    "timestamp": datetime.utcnow().isoformat(),
    "numbers": [n * n for n in range(6)],
}
print(json.dumps(result, ensure_ascii=False))`)
const filteredMemories=computed(()=>memories.value.filter(item=>{const text=`${item.key}${item.content}${item.tags.join('')}`.toLowerCase();return(!agentFilter.value||item.agentKey===agentFilter.value)&&text.includes(search.value.toLowerCase())}))
const agents=computed(()=>[...new Set(memories.value.map(item=>item.agentKey))])
async function load(){loading.value=true;try{const [m,s,r,status]=await Promise.all([api.memories(projectId),api.skills(),api.sandboxRuns(projectId),api.sandboxStatus()]);memories.value=m;skills.value=s;runs.value=r;sandbox.value=status}catch(error){app.toast('运行时加载失败',error instanceof Error?error.message:'后端暂不可用')}finally{loading.value=false}}
async function addMemory(){if(!memoryForm.value.key||!memoryForm.value.content)return;try{const item=await api.createMemory(projectId,{...memoryForm.value,tags:memoryForm.value.tags.split(',').map(v=>v.trim()).filter(Boolean)});memories.value.unshift(item);showAdd.value=false;memoryForm.value.key='';memoryForm.value.content='';app.toast('记忆已保存','该记忆将在后续 Agent 上下文中自动召回。')}catch(error){app.toast('保存失败',error instanceof Error?error.message:'请稍后重试')}}
async function removeMemory(item:MemoryRecord){try{await api.deleteMemory(projectId,item.id);memories.value=memories.value.filter(m=>m.id!==item.id);app.toast('记忆已删除','Agent 上下文将在下次构建时更新。')}catch(error){app.toast('删除失败',error instanceof Error?error.message:'请稍后重试')}}
function sampleInput(name:string):Record<string,unknown>{if(name==='requirement-analysis')return{project_name:'员工假勤管理平台',requirement:'新增部门维度的假勤报表导出，HR 管理员可按日期筛选，需要记录审计日志并限制单次 50000 条。'};if(name==='code-metrics')return{language:'python',code:'def export_report(rows):\n    if not rows:\n        return []\n    return [item.to_dict() for item in rows]'};return{changed_modules:['报表服务','假勤报表页面','权限模块'],risk_level:'medium',existing_tests:['test_leave_approval.py']}}
async function executeSkill(skill:SkillRecord){executing.value=true;try{resultRun.value=await api.executeSkill(projectId,skill.name,sampleInput(skill.name));runs.value.unshift(resultRun.value);memories.value=await api.memories(projectId);app.toast('Skill 执行完成',`${skill.displayName} 已在 ${resultRun.value.backend} 沙箱运行。`)}catch(error){app.toast('Skill 执行失败',error instanceof Error?error.message:'请检查 Skill 配置')}finally{executing.value=false}}
async function runCode(){executing.value=true;try{resultRun.value=await api.runSandbox(projectId,code.value);runs.value.unshift(resultRun.value);app.toast(resultRun.value.status==='completed'?'沙箱执行完成':'沙箱执行失败',`退出码：${resultRun.value.exitCode??'—'}`)}catch(error){app.toast('沙箱执行失败',error instanceof Error?error.message:'请稍后重试')}finally{executing.value=false}}
async function buildContext(){try{context.value=await api.agentContext(projectId,contextAgent.value,contextQuery.value);app.toast('上下文已构建',`召回 ${context.value.memories.length} 条记忆，加载 ${context.value.skills.length} 个 Skills。`)}catch(error){app.toast('构建失败',error instanceof Error?error.message:'请稍后重试')}}
onMounted(load)
</script>

<template><div class="content-width agent-runtime-page"><PageTitle eyebrow="AGENT RUNTIME" title="Agent 运行时" description="管理持久记忆、加载 Skills，并在隔离沙箱中安全执行工具代码。"><button class="button secondary" @click="load"><RefreshCcw :size="16"/>重新加载</button><button class="button primary" @click="tab='sandbox';runCode()"><Play :size="16"/>运行沙箱测试</button></PageTitle><div class="runtime-capability-cards"><article><span class="metric-icon indigo"><BrainCircuit :size="19"/></span><div><small>持久记忆</small><strong>{{memories.length}} <em>条</em></strong><p><i></i>SQLite / PostgreSQL</p></div></article><article><span class="metric-icon blue"><Sparkles :size="19"/></span><div><small>已加载 Skills</small><strong>{{skills.length}} <em>个</em></strong><p><i></i>Manifest 校验通过</p></div></article><article><span class="metric-icon green"><Terminal :size="19"/></span><div><small>沙箱后端</small><strong>{{sandbox?.activeBackend||'—'}}</strong><p><i></i>{{sandbox?.isolation||'检测中'}}</p></div></article><article><span class="metric-icon amber"><Zap :size="19"/></span><div><small>沙箱执行</small><strong>{{runs.length}} <em>次</em></strong><p><i></i>{{runs.filter(r=>r.status==='completed').length}} 次成功</p></div></article></div><div v-if="sandbox?.warnings.length" class="runtime-warning"><AlertTriangle :size="17"/><div><b>沙箱安全提示</b><p>{{sandbox.warnings[0]}}</p></div><span>生产建议：Docker + network none</span></div><div class="runtime-tabs"><button v-for="item in [['memory','持久记忆',BrainCircuit],['skills','Skill 注册表',Sparkles],['sandbox','沙箱执行',Terminal],['chat','对话',MessageCircle],['context','上下文预览',MemoryStick]]" :key="item[0] as string" :class="{active:tab===item[0]}" @click="tab=item[0] as string"><component :is="item[2]" :size="16"/>{{item[1]}}</button></div>
<section v-if="tab==='memory'" class="panel runtime-panel"><header class="table-toolbar"><div class="inline-search admin-search"><Search :size="15"/><input v-model="search" placeholder="搜索记忆内容或标签"/></div><div><button class="filter-button">{{agentFilter||'全部 Agent'}}<ChevronDown :size="14"/></button><button class="button primary" @click="showAdd=true"><Plus :size="15"/>写入记忆</button></div></header><div class="memory-list"><article v-for="item in filteredMemories" :key="item.id"><span class="memory-kind" :class="item.memoryType"><BrainCircuit :size="17"/></span><div class="memory-body"><div><code>{{item.key}}</code><span>{{item.memoryType}}</span><span>{{item.scope}}</span></div><p>{{item.content}}</p><footer><span v-for="tag in item.tags" :key="tag">#{{tag}}</span><em>Agent：{{item.agentKey}}</em><em>重要度 {{Math.round(item.importance*100)}}%</em><em>召回 {{item.accessCount}} 次</em></footer></div><button class="icon-button" @click="removeMemory(item)"><Trash2 :size="15"/></button></article><div v-if="!filteredMemories.length" class="runtime-empty"><BrainCircuit :size="25"/><b>暂无匹配记忆</b><p>写入的项目事实、历史经验和操作规范将在后续任务中自动召回。</p></div></div></section>
<section v-else-if="tab==='skills'" class="runtime-skills-grid"><article v-for="skill in skills" :key="skill.name" class="panel runtime-skill-card"><header><span><Sparkles :size="19"/></span><div><h3>{{skill.displayName}}</h3><code>{{skill.name}}@{{skill.version}}</code></div><StatusBadge status="completed" label="已加载"/></header><p>{{skill.description}}</p><div class="skill-agent-tags"><span v-for="agent in skill.agentTypes" :key="agent">{{agent}}</span></div><div class="skill-manifest-info"><span><Code2 :size="14"/>{{skill.entrypoint||'Prompt only'}}</span><span><ShieldCheck :size="14"/>SHA-256 {{skill.checksum.slice(0,8)}}</span></div><footer><div><span v-for="tag in skill.tags" :key="tag">#{{tag}}</span></div><button class="button secondary" :disabled="executing" @click="executeSkill(skill)"><LoaderCircle v-if="executing" :size="14" class="spin"/><Play v-else :size="14"/>运行 Skill</button></footer></article></section>
<section v-else-if="tab==='sandbox'" class="sandbox-console-layout"><main class="panel sandbox-editor"><header><div><span><Terminal :size="18"/></span><div><h3>Python 沙箱</h3><p>使用隔离模式执行，资源限制由后端统一控制</p></div></div><button class="button primary" :disabled="executing" @click="runCode"><LoaderCircle v-if="executing" :size="15" class="spin"/><Play v-else :size="15"/>运行代码</button></header><div class="sandbox-code"><span>1<br/>2<br/>3<br/>4<br/>5<br/>6<br/>7<br/>8<br/>9<br/>10</span><textarea v-model="code" spellcheck="false"></textarea></div><footer><span><ShieldCheck :size="13"/>{{sandbox?.isolation}}</span><span>内存 {{sandbox?.limits.memoryMb}} MB</span><span>CPU {{sandbox?.limits.cpuSeconds}}s</span><span>超时 {{sandbox?.limits.timeoutSeconds}}s</span></footer></main><aside><section class="panel sandbox-status-card"><header><h3>运行环境</h3><StatusBadge status="completed" label="可用"/></header><dl><div><dt>配置后端</dt><dd>{{sandbox?.configuredBackend}}</dd></div><div><dt>实际后端</dt><dd>{{sandbox?.activeBackend}}</dd></div><div><dt>Docker</dt><dd>{{sandbox?.dockerAvailable?'可用':'未检测到'}}</dd></div><div><dt>隔离模式</dt><dd>{{sandbox?.isolation}}</dd></div></dl></section><section class="panel sandbox-runs"><header><h3>最近执行</h3><span>{{runs.length}}</span></header><button v-for="run in runs.slice(0,6)" :key="run.id" @click="resultRun=run"><span :class="run.status"><Check v-if="run.status==='completed'" :size="13"/><X v-else :size="13"/></span><div><b>{{run.skillName||'Python 代码'}}</b><small>{{run.backend}} · {{run.resourceUsage.elapsedMs||'—'}} ms</small></div><StatusBadge :status="run.status==='completed'?'completed':'failed'" :label="run.status"/></button></section></aside></section>
<section v-else-if="tab==='chat'" class="runtime-chat-section"><ConversationPanel :project-id="projectId"/></section>
<section v-else class="context-builder"><section class="panel context-controls"><header><span><MemoryStick :size="18"/></span><div><h3>Agent 上下文构建</h3><p>预览执行任务前注入的持久记忆与 Skill 指令</p></div></header><div><label><span>Agent 类型</span><button>{{contextAgent}}<ChevronDown :size="14"/></button></label><label><span>当前任务/查询</span><textarea v-model="contextQuery"></textarea></label><button class="button primary" @click="buildContext"><BrainCircuit :size="15"/>构建运行时上下文</button></div></section><section v-if="context" class="context-result"><div class="context-result-metrics"><span>召回记忆 <b>{{context.memories.length}}</b></span><span>加载 Skills <b>{{context.skills.length}}</b></span><span>沙箱 <b>{{context.sandbox.activeBackend}}</b></span></div><article class="panel"><header><h3>Memory Prompt</h3><span>{{context.memoryPrompt.length}} chars</span></header><pre>{{context.memoryPrompt}}</pre></article><article class="panel"><header><h3>Skill Prompt</h3><span>{{context.skillPrompt.length}} chars</span></header><pre>{{context.skillPrompt}}</pre></article></section><section v-else class="panel runtime-context-empty"><BrainCircuit :size="28"/><h3>尚未构建上下文</h3><p>选择 Agent 并输入当前任务，系统会按相关性召回记忆并加载适用 Skills。</p></section></section>
<div v-if="showAdd" class="modal-layer" @click.self="showAdd=false"><section class="dialog memory-dialog"><header class="dialog-head"><div><span class="dialog-kicker">PERSISTENT MEMORY</span><h2>写入 Agent 记忆</h2></div><button class="icon-button" @click="showAdd=false"><X :size="18"/></button></header><div class="dialog-body"><div class="memory-form-grid"><label><span>Agent Key</span><input v-model="memoryForm.agentKey"/></label><label><span>记忆类型</span><select v-model="memoryForm.memoryType"><option value="semantic">semantic · 项目事实</option><option value="episodic">episodic · 执行经验</option><option value="procedural">procedural · 操作规范</option><option value="working">working · 临时工作记忆</option></select></label><label><span>记忆 Key</span><input v-model="memoryForm.key" placeholder="例如：export-limit"/></label><label><span>作用域</span><select v-model="memoryForm.scope"><option value="project">project · 全项目</option><option value="agent">agent · 指定 Agent</option><option value="working">working · 当前工作</option></select></label><label class="full"><span>记忆内容</span><textarea v-model="memoryForm.content" placeholder="记录项目事实、用户偏好、历史经验或操作规范…"></textarea></label><label class="full"><span>标签（逗号分隔）</span><input v-model="memoryForm.tags" placeholder="export, constraint, security"/></label><label class="full importance-control"><span>重要度</span><input type="range" min="0" max="1" step=".05" v-model="memoryForm.importance"/><b>{{Math.round(memoryForm.importance*100)}}%</b></label></div></div><footer class="dialog-foot"><button class="button ghost" @click="showAdd=false">取消</button><button class="button primary" :disabled="!memoryForm.key||!memoryForm.content" @click="addMemory"><BrainCircuit :size="15"/>保存记忆</button></footer></section></div>
<div v-if="resultRun" class="side-drawer-backdrop" @click.self="resultRun=null"><aside class="side-drawer result-drawer"><header><div><h3>沙箱执行结果</h3><p>{{resultRun.id}}</p></div><button class="icon-button" @click="resultRun=null"><X :size="18"/></button></header><div class="result-summary"><StatusBadge :status="resultRun.status==='completed'?'completed':'failed'" :label="resultRun.status"/><span>Backend: {{resultRun.backend}}</span><span>Exit: {{resultRun.exitCode}}</span><span>{{resultRun.resourceUsage.elapsedMs}} ms</span></div><section><h4>结构化结果</h4><pre>{{JSON.stringify(resultRun.result,null,2)}}</pre></section><section><h4>标准输出</h4><pre>{{resultRun.stdout||'(empty)'}}</pre></section><section v-if="resultRun.stderr"><h4>标准错误</h4><pre class="stderr">{{resultRun.stderr}}</pre></section></aside></div></div></template>
