<script setup lang="ts">
import { ref } from 'vue'
import { Archive, Box, CheckCircle2, ChevronRight, CloudDownload, Code2, Database, ExternalLink, FileCode2, FileText, Folder, Package, Rocket, Search, Server } from 'lucide-vue-next'
import { useAppStore } from '../stores/app'
import PageTitle from '../components/PageTitle.vue'
import StatusBadge from '../components/StatusBadge.vue'
const app=useAppStore();const tab=ref('code')
const files=['frontend','backend','docs','tests','docker-compose.yml','README.md']
</script>
<template>
  <div class="content-width artifacts-page"><PageTitle title="产物中心" description="查看、下载项目代码、文档、测试报告和部署产物。"><button class="button secondary" @click="app.toast('正在打包','项目代码 ZIP 将在打包完成后自动下载。')"><CloudDownload :size="16"/>下载代码</button><button class="button primary" @click="app.toast('应用已打开','正在新窗口打开测试环境。')"><ExternalLink :size="16"/>访问应用</button></PageTitle>
    <div class="artifact-metrics"><article><span class="metric-icon indigo"><Code2 :size="19"/></span><div><small>代码仓库</small><strong>v1.2.0</strong><span>86 个文件 · 8.4 MB</span></div></article><article><span class="metric-icon green"><CheckCircle2 :size="19"/></span><div><small>测试报告</small><strong>98.4%</strong><span>149 / 152 通过</span></div></article><article><span class="metric-icon blue"><Box :size="19"/></span><div><small>Docker 镜像</small><strong>468 MB</strong><span>registry/app:v1.2.0</span></div></article><article><span class="metric-icon amber"><Rocket :size="19"/></span><div><small>生产部署</small><strong>运行中</strong><span>已稳定运行 4 天</span></div></article></div>
    <div class="artifact-layout"><aside class="artifact-nav"><button :class="{active:tab==='code'}" @click="tab='code'"><Code2 :size="17"/>代码仓库<span>86</span></button><button :class="{active:tab==='docs'}" @click="tab='docs'"><FileText :size="17"/>项目文档<span>5</span></button><button :class="{active:tab==='reports'}" @click="tab='reports'"><FileCode2 :size="17"/>测试报告<span>4</span></button><button :class="{active:tab==='images'}" @click="tab='images'"><Box :size="17"/>部署镜像<span>3</span></button></aside><section class="panel artifact-browser"><header class="panel-title"><div><h3>{{tab==='code'?'代码仓库':tab==='docs'?'项目文档':tab==='reports'?'测试报告':'部署镜像'}}</h3><p>最近更新：今天 11:06</p></div><div class="inline-search"><Search :size="15"/><input placeholder="搜索产物"/></div></header>
    <div v-if="tab==='code'" class="repo-browser"><div class="repo-head"><span>main</span><code>3a94f21</code><p>feat: support configurable approval workflow</p><small>4 天前</small></div><button v-for="file in files" :key="file"><Folder v-if="!file.includes('.')" :size="17"/><FileCode2 v-else :size="17"/><strong>{{file}}</strong><span>{{file.includes('.')?'更新项目部署说明':'更新三级审批流程'}}</span><small>4 天前</small><ChevronRight :size="15"/></button></div><div v-else class="document-cards"><article v-for="(doc,i) in (tab==='docs'?['需求说明书','架构设计文档','API 接口文档','数据库设计文档','部署文档']:tab==='reports'?['回归测试报告','E2E 测试报告','代码覆盖率报告','安全扫描报告']:['app:v1.2.0','app:v1.1.1','app:v1.1.0'])" :key="doc"><span><component :is="tab==='images'?Box:FileText" :size="20"/></span><div><strong>{{doc}}</strong><p>{{tab==='images'?'linux/amd64 · 468 MB':'Markdown · 已同步 v1.2.0 变更'}}</p></div><StatusBadge status="completed" :label="tab==='images'&&i===0?'运行中':'已就绪'"/><ChevronRight :size="16"/></article></div></section></div>
  </div>
</template>
