<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { AlertTriangle, Box, Check, CheckCircle2, ChevronDown, Clock3, Cloud, ExternalLink, GitCommit, Globe2, LoaderCircle, MoreHorizontal, RefreshCcw, Rocket, RotateCcw, Server, ShieldCheck, Square, Terminal, X, XCircle } from 'lucide-vue-next'
import { api, type AgentBuildRecord, type ApplicationDeploymentRecord, type DeploymentRuntimeStatus } from '../api/client'
import { useAppStore } from '../stores/app'
import PageTitle from '../components/PageTitle.vue'
import StatusBadge from '../components/StatusBadge.vue'

const route=useRoute();const projectId=String(route.params.id);const app=useAppStore();const environment=ref<'test'|'production'>('test');const showDeploy=ref(false);const deploying=ref(false);const runtime=ref<DeploymentRuntimeStatus|null>(null);const realDeployments=ref<ApplicationDeploymentRecord[]>([]);const builds=ref<AgentBuildRecord[]>([]);const selected=ref<ApplicationDeploymentRecord|null>(null);let timer:number|undefined
const deployableBuild=computed(()=>builds.value.find(item=>item.status==='completed'))
const runningDeployment=computed(()=>realDeployments.value.find(item=>item.status==='running'&&item.environment===environment.value))
const hasActive=computed(()=>realDeployments.value.some(item=>['pending','building','deploying'].includes(item.status)))
const stages=[['preparing','准备配置'],['building_backend','后端镜像'],['building_frontend','前端镜像'],['starting','启动容器'],['smoke_testing','冒烟测试'],['completed','运行中']]
async function load(){try{const [docker,deployments,history]=await Promise.all([api.deploymentRuntimeStatus(),api.applicationDeployments(projectId),api.agentBuilds(projectId)]);runtime.value=docker;realDeployments.value=deployments;builds.value=history;if(!selected.value&&deployments.length)selected.value=await api.applicationDeployment(projectId,deployments[0].id)}catch(error){app.toast('部署数据加载失败',error instanceof Error?error.message:'请稍后重试')}}
async function refresh(){await load();if(selected.value){const latest=realDeployments.value.find(item=>item.id===selected.value?.id);if(latest)selected.value=await api.applicationDeployment(projectId,latest.id)}}
async function deploy(){if(!deployableBuild.value||!runtime.value?.ready)return;deploying.value=true;try{const item=await api.createApplicationDeployment(projectId,deployableBuild.value.id,environment.value);realDeployments.value.unshift(item);selected.value=item;showDeploy.value=false;app.toast('真实部署已启动','正在构建前后端镜像并准备冒烟测试。')}catch(error){app.toast('部署启动失败',error instanceof Error?error.message:'请稍后重试')}finally{deploying.value=false}}
async function choose(item:ApplicationDeploymentRecord){selected.value=await api.applicationDeployment(projectId,item.id)}
async function stop(item:ApplicationDeploymentRecord){try{await api.stopApplicationDeployment(projectId,item.id);app.toast('部署已停止','容器和隔离网络已清理，镜像仍保留。');await refresh()}catch(error){app.toast('停止失败',error instanceof Error?error.message:'请稍后重试')}}
async function rollback(item:ApplicationDeploymentRecord){try{const next=await api.rollbackApplicationDeployment(projectId,item.id);realDeployments.value.unshift(next);selected.value=next;app.toast('回滚部署已启动',`正在使用 ${item.version} 的源码重新创建容器。`)}catch(error){app.toast('回滚失败',error instanceof Error?error.message:'请稍后重试')}}
function formatTime(value:string|null){return value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—'}
function stageState(key:string,item:ApplicationDeploymentRecord){if(item.status==='running')return'done';if(item.status==='failed'&&item.currentStage===key)return'failed';const index=stages.findIndex(s=>s[0]===key),current=stages.findIndex(s=>s[0]===item.currentStage);return index<current?'done':index===current?'active':''}
onMounted(async()=>{await load();timer=window.setInterval(()=>{if(hasActive.value)refresh()},1800)})
onUnmounted(()=>timer&&clearInterval(timer))
</script>

<template><div class="content-width deployments-page"><PageTitle title="部署中心" description="将通过质量门禁的 Agent 构建发布为真实 Docker 应用。"><button class="button secondary" @click="refresh"><RefreshCcw :size="16"/>刷新</button><button class="button primary" :disabled="!runtime?.ready||!deployableBuild||hasActive" @click="showDeploy=true"><Rocket :size="16"/>部署成功构建</button></PageTitle>
<section v-if="runtime" :class="['docker-runtime-banner',runtime.ready?'ready':'unavailable']"><span><Server :size="20"/></span><div><small>APPLICATION RUNTIME</small><h3>{{runtime.ready?`Docker ${runtime.dockerVersion}`:'Docker daemon 不可用'}}</h3><p>{{runtime.message}}</p></div><span v-if="runtime.ready" class="gateway-online"><i></i>{{runtime.runningDeployments}} 个运行中</span><StatusBadge v-else status="paused" label="不可部署"/></section>
<div class="environment-switch"><div><button :class="{active:environment==='production'}" @click="environment='production'"><span class="env-dot prod"></span>生产环境</button><button :class="{active:environment==='test'}" @click="environment='test'"><span class="env-dot test"></span>测试环境</button></div><span>Docker 容器隔离 · 独立端口 · 自动冒烟测试</span></div>
<section v-if="runningDeployment" class="current-deployment real"><div class="deployment-main"><div class="deploy-app-icon"><Rocket :size="24"/><i></i></div><div><span class="deploy-label">REAL RUNNING DEPLOYMENT</span><div class="deploy-version-line"><h2>{{runningDeployment.version}}</h2><StatusBadge status="running" label="运行正常"/></div><p><Globe2 :size="14"/><a :href="runningDeployment.deployUrl" target="_blank">{{runningDeployment.deployUrl}}</a><ExternalLink :size="13"/></p></div></div><div class="deployment-info"><div><small>环境</small><strong>{{runningDeployment.environment}}</strong></div><div><small>前端镜像</small><strong>{{runningDeployment.frontendImage.split(':').pop()}}</strong></div><div><small>主机端口</small><strong>{{runningDeployment.hostPort}}</strong></div><div><small>健康检查</small><strong class="green-text">已通过</strong></div></div><button class="button danger-ghost" @click="stop(runningDeployment)"><Square :size="14"/>停止</button></section>
<section v-if="selected" class="panel real-deployment-progress"><header><div><StatusBadge :status="selected.status==='running'?'running':selected.status==='failed'?'failed':'executing'"/><span>{{selected.version}}</span><span>{{selected.environment}}</span></div><strong>{{selected.progress}}%</strong></header><div class="real-deploy-stages"><template v-for="(stage,i) in stages" :key="stage[0]"><div :class="stageState(stage[0],selected)"><span><Check v-if="stageState(stage[0],selected)==='done'" :size="13"/><XCircle v-else-if="stageState(stage[0],selected)==='failed'" :size="13"/>{{!stageState(stage[0],selected)?i+1:''}}</span><b>{{stage[1]}}</b></div><i v-if="i<stages.length-1" :class="{done:stageState(stage[0],selected)==='done'}"></i></template></div><div class="real-deploy-track"><i :style="{width:`${selected.progress}%`}"></i></div><div class="deployment-live-logs"><div v-for="log in selected.logs.slice(-8)" :key="log.id" :class="log.level"><time>{{formatTime(log.createdAt)}}</time><span>{{log.stage}}</span><p>{{log.message}}</p></div></div><footer v-if="selected.errorMessage"><AlertTriangle :size="15"/><span>{{selected.errorMessage}}</span></footer></section>
<div class="deployment-grid"><section class="panel runtime-health"><header class="panel-title"><div><h3>容器安全与资源</h3><p>当前部署默认限制</p></div><span class="healthy-text"><i></i>{{runtime?.ready?'运行时就绪':'等待 Docker'}}</span></header><div class="runtime-metrics"><article><span><Server :size="18"/></span><div><small>后端内存</small><strong>512 MB</strong><em>CPU 1 Core</em></div></article><article><span><Cloud :size="18"/></span><div><small>前端内存</small><strong>256 MB</strong><em>CPU 0.5 Core</em></div></article><article><span><ShieldCheck :size="18"/></span><div><small>容器权限</small><strong>Cap Drop</strong><em>No New Privileges</em></div></article><article><span><Box :size="18"/></span><div><small>网络隔离</small><strong>独立 Network</strong><em>仅前端发布端口</em></div></article></div><div class="deployment-security-note"><ShieldCheck :size="16"/><p>后端不直接暴露主机端口，前端 Nginx 通过隔离网络代理 `/api`；新版本冒烟测试通过后才停止旧容器。</p></div></section><section class="panel release-readiness"><header class="panel-title"><div><h3>可部署构建</h3><p>最近通过全部质量门禁的版本</p></div><span class="readiness-score">{{deployableBuild?'100%':'—'}}</span></header><div v-if="deployableBuild" class="deployable-build"><span><CheckCircle2 :size="20"/></span><div><b>Build {{deployableBuild.id.slice(-8)}}</b><p>{{deployableBuild.requirement.slice(0,70)}}…</p><small>覆盖率 {{deployableBuild.coverage??'—'}}% · {{deployableBuild.generatedFiles.length}} 文件</small></div></div><div v-else class="deployable-empty"><Rocket :size="22"/><p>请先在 AI 全栈构建页面完成一个真实构建</p></div></section></div>
<section class="panel deployment-history"><header class="panel-title"><div><h3>真实部署历史</h3><p>镜像、容器、冒烟测试和版本切换记录</p></div><button class="filter-button">{{environment==='test'?'测试环境':'生产环境'}}<ChevronDown :size="14"/></button></header><table class="data-table"><thead><tr><th>版本</th><th>环境</th><th>状态</th><th>访问地址</th><th>冒烟测试</th><th>部署时间</th><th></th></tr></thead><tbody><tr v-for="item in realDeployments.filter(d=>d.environment===environment)" :key="item.id" @click="choose(item)"><td><b>{{item.version}}</b><small>{{item.id.slice(-8)}}</small></td><td><span class="environment-chip" :class="item.environment==='production'?'prod':'test'">{{item.environment}}</span></td><td><StatusBadge :status="item.status==='running'?'running':item.status==='failed'?'failed':'paused'" :label="item.status"/></td><td><a v-if="item.deployUrl" :href="item.deployUrl" target="_blank">{{item.deployUrl}}</a><span v-else>—</span></td><td><span :class="item.smokeResult.passed?'green-text':''">{{item.smokeResult.passed?'通过':'—'}}</span></td><td>{{formatTime(item.createdAt)}}</td><td><button v-if="item.status==='stopped'" class="text-button" @click.stop="rollback(item)"><RotateCcw :size="13"/>回滚</button><button v-else class="icon-button"><MoreHorizontal :size="16"/></button></td></tr><tr v-if="!realDeployments.filter(d=>d.environment===environment).length"><td colspan="7"><div class="deployment-empty-row">该环境暂无真实部署记录</div></td></tr></tbody></table></section>
<div v-if="showDeploy" class="modal-layer" @click.self="!deploying&&(showDeploy=false)"><section class="dialog deploy-dialog"><header class="dialog-head"><div><span class="dialog-kicker">REAL DOCKER DEPLOYMENT</span><h2>部署生成应用</h2></div><button class="icon-button" @click="showDeploy=false"><X :size="18"/></button></header><div class="dialog-body"><div class="deploy-version-card"><span><Rocket :size="21"/></span><div><small>已通过全部质量门禁</small><strong>Build {{deployableBuild?.id.slice(-8)}}</strong><p>{{deployableBuild?.generatedFiles.length}} 个源码文件 · 覆盖率 {{deployableBuild?.coverage??'—'}}%</p></div><CheckCircle2 :size="20"/></div><label class="form-label with-hint">目标环境</label><div class="environment-options"><label :class="{selected:environment==='test'}" @click="environment='test'"><input type="radio"/><span class="env-dot test"></span><div><b>测试环境</b><small>自动构建并执行冒烟测试</small></div><Check v-if="environment==='test'" :size="15"/></label><label :class="{selected:environment==='production'}" @click="environment='production'"><input type="radio"/><span class="env-dot prod"></span><div><b>生产环境</b><small>成功后安全切换旧版本</small></div><Check v-if="environment==='production'" :size="15"/></label></div><div class="warning-box"><ShieldCheck :size="17"/><div><b>安全版本替换</b><span>新容器通过首页与健康检查后才停止旧容器；历史镜像继续保留，可发起回滚。</span></div></div></div><footer class="dialog-foot"><button class="button ghost" @click="showDeploy=false">取消</button><button class="button primary" :disabled="deploying" @click="deploy"><LoaderCircle v-if="deploying" :size="15" class="spin"/><Rocket v-else :size="16"/>确认真实部署</button></footer></section></div></div></template>
