<script setup lang="ts">
import { ref } from 'vue'
import { AlertTriangle, ArrowLeft, Check, CheckCircle2, ChevronRight, Clock3, Code2, Database, ExternalLink, FileCode2, GitBranch, GitCompareArrows, ListChecks, Rocket, ShieldCheck, Sparkles, TestTube2, UserRound } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import StatusBadge from '../components/StatusBadge.vue'

const route=useRoute();const router=useRouter();const tab=ref('overview');const tabs=[['overview','迭代概览'],['tasks','任务与日志'],['changes','代码变更'],['tests','测试报告'],['deployment','部署结果']]
const taskRows=[{name:'需求解析与影响分析',agent:'需求分析智能体',short:'RA',status:'completed',duration:'12m'},{name:'增量技术方案设计',agent:'架构设计智能体',short:'AR',status:'completed',duration:'18m'},{name:'开发报表导出接口',agent:'后端开发智能体',short:'BE',status:'completed',duration:'48m'},{name:'新增导出交互组件',agent:'前端开发智能体',short:'FE',status:'completed',duration:'36m'},{name:'增量代码审查',agent:'代码审查智能体',short:'CR',status:'completed',duration:'21m'},{name:'回归测试与质量验证',agent:'测试工程师智能体',short:'QA',status:'in_progress',duration:'31m'}]
</script>

<template><div class="content-width iteration-detail-page"><button class="back-link" @click="router.push(`/projects/${route.params.id}/iterations`)"><ArrowLeft :size="16"/>返回迭代历史</button><section class="iteration-detail-hero"><div><span class="version-badge type-feature"><GitBranch :size="16"/>v1.3.0</span><StatusBadge status="executing"/><span class="iteration-sequence">第 5 次迭代</span><h1>新增报表 Excel 导出</h1><p>支持按部门、日期和审批状态筛选后导出假勤明细，增加异步进度反馈。</p><div><span><UserRound :size="14"/>林嘉 提出</span><span><Clock3 :size="14"/>2026-08-17 09:31</span></div></div><div class="iteration-hero-stats"><div><small>变更文件</small><strong>12</strong></div><div><small>代码变化</small><strong class="green-text">+684</strong><em>−57</em></div><div><small>测试通过</small><strong>92%</strong></div></div></section><div class="iteration-detail-tabs"><button v-for="item in tabs" :key="item[0]" :class="{active:tab===item[0]}" @click="tab=item[0]">{{item[1]}}</button></div>
<section v-if="tab==='overview'" class="iteration-overview-grid"><div><article class="panel change-request-card"><header class="panel-title"><div><h3>变更需求原文</h3><p>CHANGE REQUEST</p></div></header><blockquote>“新增假勤报表导出功能，支持按部门、日期和审批状态筛选，并导出为 Excel 文件。导出数据量较大时需要显示处理进度。”</blockquote><footer><span class="member-avatar">LJ</span><div><b>林嘉</b><small>人力资源部 · 项目所有者</small></div><span>今天 09:31</span></footer></article><article class="panel impact-detail-card"><header class="panel-title"><div><h3>变更影响分析</h3><p>由项目经理智能体生成</p></div><span class="risk-low"><ShieldCheck :size="15"/>低风险</span></header><div class="impact-detail-metrics"><div><span class="metric-icon indigo"><FileCode2 :size="18"/></span><p><small>影响模块</small><strong>3 个</strong></p></div><div><span class="metric-icon blue"><Code2 :size="18"/></span><p><small>预计文件</small><strong>8–12 个</strong></p></div><div><span class="metric-icon green"><Database :size="18"/></span><p><small>Schema 变更</small><strong>无</strong></p></div></div><div class="affected-modules"><div><span>后端 · 报表服务</span><b>新增异步导出接口</b></div><div><span>前端 · 假勤报表</span><b>新增导出交互</b></div><div><span>权限 · 数据导出</span><b>复用既有规则</b></div></div><div class="warning-box"><AlertTriangle :size="17"/><div><b>分析建议</b><span>大数据量导出采用异步任务，单次限制 50,000 条，完成后通过站内通知提供下载链接。</span></div></div></article></div><aside><section class="panel iteration-progress-card"><header class="panel-title"><div><h3>执行进度</h3><p>6 / 7 项任务</p></div><strong>78%</strong></header><div class="vertical-stage-list"><div class="done"><span><Check :size="14"/></span><p><b>影响分析</b><small>09:31 — 09:43</small></p></div><div class="done"><span><Check :size="14"/></span><p><b>增量设计与开发</b><small>09:45 — 10:54</small></p></div><div class="done"><span><Check :size="14"/></span><p><b>代码审查</b><small>10:58 — 11:19</small></p></div><div class="active"><span>4</span><p><b>回归测试</b><small>11:22 — 进行中</small></p></div><div><span>5</span><p><b>部署验证</b><small>等待执行</small></p></div></div></section><section class="panel iteration-links"><h3>相关链接</h3><button><GitCompareArrows :size="16"/>与 v1.2.0 对比<ChevronRight :size="15"/></button><button><ListChecks :size="16"/>查看任务树<ChevronRight :size="15"/></button><button><Rocket :size="16"/>部署中心<ChevronRight :size="15"/></button></section></aside></section>
<section v-else-if="tab==='tasks'" class="panel iteration-tab-panel"><header class="panel-title"><div><h3>本次迭代任务</h3><p>按执行顺序展示全部智能体任务</p></div></header><div class="iteration-task-table"><div v-for="(task,i) in taskRows" :key="task.name"><span class="task-order">{{String(i+1).padStart(2,'0')}}</span><span class="agent-square">{{task.short}}</span><p><b>{{task.name}}</b><small>{{task.agent}}</small></p><StatusBadge :status="task.status"/><span>{{task.duration}}</span><button class="text-button">查看日志<ChevronRight :size="14"/></button></div></div></section>
<section v-else-if="tab==='changes'" class="panel iteration-tab-panel"><header class="panel-title"><div><h3>代码变更摘要</h3><p>12 个文件，+684 / −57 行</p></div><button class="button secondary"><GitCompareArrows :size="15"/>完整 Diff</button></header><div class="change-file-list"><div v-for="file in [['backend/app/api/export.py','A','+126',''],['backend/app/services/export.py','A','+214',''],['frontend/src/components/ExportDialog.vue','A','+168',''],['frontend/src/views/Reports.vue','M','+84','−31'],['tests/export/test_report_export.py','A','+186','']]" :key="file[0]"><FileCode2 :size="16"/><code>{{file[0]}}</code><em :class="file[1]==='A'?'added':'modified'">{{file[1]}}</em><b>{{file[2]}}</b><span>{{file[3]}}</span></div></div></section>
<section v-else-if="tab==='tests'" class="panel iteration-tab-panel"><header class="panel-title"><div><h3>回归测试报告</h3><p>最后更新：今天 11:53</p></div><StatusBadge status="testing" label="执行中"/></header><div class="test-report-summary"><div class="test-ring"><strong>92<small>%</small></strong></div><div><h3>140 / 152 项已通过</h3><p>当前未发现已有功能回归问题</p><div><span><i class="pass"></i>通过 140</span><span><i class="running"></i>执行中 12</span><span><i class="fail"></i>失败 0</span></div></div></div><div class="test-suites"><article><CheckCircle2 :size="18"/><div><b>既有功能回归</b><small>104 / 104 通过</small></div><strong>100%</strong></article><article><CheckCircle2 :size="18"/><div><b>导出功能单元测试</b><small>24 / 24 通过</small></div><strong>100%</strong></article><article class="running"><TestTube2 :size="18"/><div><b>端到端与性能测试</b><small>12 / 24 已完成</small></div><strong>50%</strong></article></div></section>
<section v-else class="panel iteration-tab-panel empty-deployment-result"><span><Rocket :size="27"/></span><h3>等待回归测试完成</h3><p>全部测试通过后，将自动构建 v1.3.0 镜像并进入测试环境部署。</p><button class="button secondary">前往部署中心<ExternalLink :size="15"/></button></section></div></template>
