<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../api/client'
import { Activity, Check, ChevronDown, Clock3, Mail, MoreHorizontal, Plus, Search, ShieldCheck, UserCheck, UserPlus, Users, X } from 'lucide-vue-next'
import { useAppStore } from '../stores/app'
import PageTitle from '../components/PageTitle.vue'
import StatusBadge from '../components/StatusBadge.vue'

const route=useRoute();const projectId=String(route.params.id);const app=useAppStore();const tab=ref('members');const search=ref('');const showInvite=ref(false);const inviteEmail=ref('');const inviteRole=ref('项目成员')
const members=ref([{name:'林嘉',initial:'LJ',email:'lin.jia@company.com',role:'项目所有者',department:'人力资源部',status:'online',joined:'2026-07-29',last:'当前在线'},{name:'赵玮',initial:'ZW',email:'zhao.wei@company.com',role:'协管员',department:'信息技术部',status:'online',joined:'2026-07-30',last:'当前在线'},{name:'陈屿',initial:'CY',email:'chen.yu@company.com',role:'项目成员',department:'人力资源部',status:'offline',joined:'2026-08-01',last:'2 小时前'},{name:'杨涵',initial:'YH',email:'yang.han@company.com',role:'只读用户',department:'审计与风控部',status:'offline',joined:'2026-08-03',last:'昨天 16:20'}])
const filtered=computed(()=>members.value.filter(m=>`${m.name}${m.email}${m.department}`.toLowerCase().includes(search.value.toLowerCase())))
const activities=[{name:'赵玮',initial:'ZW',action:'确认了 v1.3.0 变更影响分析',target:'新增报表 Excel 导出',time:'今天 09:31',type:'需求变更'},{name:'林嘉',initial:'LJ',action:'向测试工程师发送干预指令',target:'重点验证 5 万条以上数据导出',time:'今天 11:41',type:'人工干预'},{name:'陈屿',initial:'CY',action:'评论了架构设计文档',target:'建议将导出任务队列与通知解耦',time:'昨天 17:20',type:'评论'},{name:'赵玮',initial:'ZW',action:'执行了生产部署',target:'v1.2.0',time:'2026-08-12 16:42',type:'部署'}]
async function loadMembers(){try{const rows=await api.projectMembers(projectId);members.value=rows.map(item=>({name:item.displayName,initial:item.displayName.slice(-2).toUpperCase(),email:item.email,role:item.role==='owner'?'项目所有者':item.role==='co_manager'?'协管员':item.role==='viewer'?'只读用户':'项目成员',department:item.department,status:'offline',joined:item.joinedAt.slice(0,10),last:'最近登录'}))}catch{app.toast('成员加载失败','继续显示演示成员数据。')}}
async function invite(){if(!inviteEmail.value)return;try{const role=inviteRole.value==='协管员'?'co_manager':inviteRole.value==='只读用户'?'viewer':'member';await api.addProjectMember(projectId,inviteEmail.value,role);showInvite.value=false;app.toast('成员已添加',`${inviteEmail.value} 已加入项目。`);inviteEmail.value='';await loadMembers()}catch(error){app.toast('添加失败',error instanceof Error?error.message:'请稍后重试')}}
onMounted(loadMembers)
</script>

<template>
  <div class="content-width members-page">
    <PageTitle title="成员与协作" description="管理项目成员权限，并追踪团队关键操作。"><button class="button primary" @click="showInvite=true"><UserPlus :size="16"/>邀请成员</button></PageTitle>
    <div class="member-metrics"><article><span class="metric-icon indigo"><Users :size="19"/></span><div><small>项目成员</small><strong>4</strong><em>来自 3 个部门</em></div></article><article><span class="metric-icon green"><UserCheck :size="19"/></span><div><small>当前在线</small><strong>2</strong><em>正在查看此项目</em></div></article><article><span class="metric-icon blue"><ShieldCheck :size="19"/></span><div><small>可干预成员</small><strong>2</strong><em>所有者与协管员</em></div></article><article><span class="metric-icon amber"><Activity :size="19"/></span><div><small>本周协作</small><strong>28</strong><em>次关键操作</em></div></article></div>
    <div class="members-tabs"><button :class="{active:tab==='members'}" @click="tab='members'"><Users :size="16"/>成员列表</button><button :class="{active:tab==='activity'}" @click="tab='activity'"><Activity :size="16"/>协作日志</button></div>
    <section v-if="tab==='members'" class="panel members-table-panel"><header class="table-toolbar"><div class="inline-search"><Search :size="15"/><input v-model="search" placeholder="搜索成员、邮箱或部门"/></div><div><button class="filter-button">全部角色<ChevronDown :size="14"/></button><button class="filter-button">全部状态<ChevronDown :size="14"/></button></div></header><table class="data-table members-table"><thead><tr><th>成员</th><th>项目角色</th><th>所属部门</th><th>加入时间</th><th>最近活跃</th><th></th></tr></thead><tbody><tr v-for="member in filtered" :key="member.email"><td><div class="member-cell"><span class="member-avatar">{{member.initial}}<i v-if="member.status==='online'"></i></span><div><b>{{member.name}}<em v-if="member.role==='项目所有者'">我</em></b><small>{{member.email}}</small></div></div></td><td><span class="role-chip" :class="member.role==='项目所有者'?'owner':member.role==='协管员'?'manager':''">{{member.role}}</span></td><td>{{member.department}}</td><td>{{member.joined}}</td><td><span :class="['presence',member.status]"><i></i>{{member.last}}</span></td><td><button class="icon-button"><MoreHorizontal :size="17"/></button></td></tr></tbody></table></section>
    <section v-else class="panel collaboration-log"><header class="table-toolbar"><div><strong>项目协作日志</strong><span>记录需求、干预、部署等关键操作</span></div><button class="filter-button">最近 30 天<ChevronDown :size="14"/></button></header><div class="collab-timeline"><article v-for="item in activities" :key="item.time"><span class="member-avatar">{{item.initial}}</span><div><p><b>{{item.name}}</b> {{item.action}}</p><strong>{{item.target}}</strong><small><Clock3 :size="13"/>{{item.time}}<i></i>{{item.type}}</small></div><button class="text-button">查看详情</button></article></div></section>
    <div v-if="showInvite" class="modal-layer" @click.self="showInvite=false"><section class="dialog invite-dialog"><header class="dialog-head"><div><span class="dialog-kicker">INVITE MEMBER</span><h2>邀请项目成员</h2></div><button class="icon-button" @click="showInvite=false"><X :size="18"/></button></header><div class="dialog-body"><label class="form-label">企业邮箱</label><div class="email-entry"><Mail :size="17"/><input v-model="inviteEmail" placeholder="name@company.com"/></div><label class="form-label with-hint">项目角色</label><div class="role-options"><label v-for="role in ['协管员','项目成员','只读用户']" :key="role" :class="{selected:inviteRole===role}"><input type="radio" v-model="inviteRole" :value="role"/><span><Check :size="14"/></span><div><b>{{role}}</b><small>{{role==='协管员'?'可编辑需求和干预任务':role==='项目成员'?'可查看、评论项目内容':'仅查看已授权内容'}}</small></div></label></div></div><footer class="dialog-foot"><button class="button ghost" @click="showInvite=false">取消</button><button class="button primary" :disabled="!inviteEmail" @click="invite"><UserPlus :size="16"/>发送邀请</button></footer></section></div>
  </div>
</template>
