<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Activity, Bot, BrainCircuit, ChevronDown, Clock3, Copy, Cpu, Database, MoreHorizontal, Plus, Search, ShieldCheck, Sparkles, Terminal, TestTube2, ToggleLeft, Wrench } from 'lucide-vue-next'
import PageTitle from '../../components/PageTitle.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { useAppStore } from '../../stores/app'

const router=useRouter();const app=useAppStore();const query=ref('');const agents=ref([{id:'project-manager',name:'项目经理',key:'project-manager',icon:'PM',description:'需求理解、任务拆解、智能体协调与项目风险管理',model:'deepseek-chat',tools:8,skills:5,success:96.8,duration:'18m',runs:284,status:true,color:'indigo'},{id:'architect',name:'架构设计师',key:'architect',icon:'AR',description:'技术选型、系统架构、数据库设计与增量方案评审',model:'qwen-max',tools:7,skills:6,success:94.2,duration:'24m',runs:196,status:true,color:'blue'},{id:'frontend',name:'前端开发工程师',key:'frontend-developer',icon:'FE',description:'Vue 3 前端开发、组件设计、交互与可访问性实现',model:'deepseek-coder',tools:10,skills:8,success:92.6,duration:'42m',runs:318,status:true,color:'purple'},{id:'backend',name:'后端开发工程师',key:'backend-developer',icon:'BE',description:'FastAPI 服务、业务逻辑、接口与数据库访问实现',model:'deepseek-coder',tools:12,skills:9,success:93.7,duration:'48m',runs:326,status:true,color:'green'},{id:'reviewer',name:'代码审查工程师',key:'code-reviewer',icon:'CR',description:'代码规范、安全风险、兼容性与最佳实践审查',model:'qwen-max',tools:6,skills:7,success:97.4,duration:'16m',runs:301,status:true,color:'amber'},{id:'tester',name:'测试工程师',key:'test-engineer',icon:'QA',description:'单元、集成、E2E 与回归测试生成及执行',model:'deepseek-coder',tools:11,skills:8,success:95.1,duration:'31m',runs:292,status:true,color:'cyan'},{id:'deployer',name:'部署工程师',key:'deployment-engineer',icon:'DO',description:'Docker 镜像构建、环境部署、健康检查与回滚',model:'qwen-plus',tools:9,skills:5,success:98.2,duration:'8m',runs:188,status:true,color:'slate'},{id:'database',name:'数据库工程师',key:'database-engineer',icon:'DB',description:'Schema 设计、查询优化、迁移脚本与数据安全',model:'qwen-max',tools:8,skills:6,success:91.8,duration:'27m',runs:116,status:false,color:'rose'}])
const filtered=computed(()=>agents.value.filter(a=>`${a.name}${a.key}${a.description}`.toLowerCase().includes(query.value.toLowerCase())))
function toggle(agent:typeof agents.value[number]){agent.status=!agent.status;app.toast(agent.status?'智能体已启用':'智能体已停用',`${agent.name}配置已更新。`)}
</script>
<template><div class="content-width admin-page agent-types-page"><PageTitle eyebrow="PLATFORM ADMIN" title="智能体类型" description="配置平台中的专业智能体角色、模型、工具与技能。"><button class="button secondary"><Activity :size="16"/>执行数据</button><button class="button primary" @click="router.push('/admin/agent-types/new')"><Plus :size="16"/>创建智能体类型</button></PageTitle><div class="admin-metrics"><article><span class="metric-icon indigo"><Bot :size="19"/></span><div><small>智能体类型</small><strong>8</strong><em>7 个已启用</em></div></article><article><span class="metric-icon green"><Activity :size="19"/></span><div><small>本月执行</small><strong>2,041</strong><em class="green-text">+18.6%</em></div></article><article><span class="metric-icon blue"><ShieldCheck :size="19"/></span><div><small>平均成功率</small><strong>95.0%</strong><em class="green-text">+1.4%</em></div></article><article><span class="metric-icon amber"><Cpu :size="19"/></span><div><small>Token 消耗</small><strong>42.8M</strong><em>预算内 68%</em></div></article></div><section class="panel agent-list-panel"><header class="table-toolbar"><div class="inline-search admin-search"><Search :size="15"/><input v-model="query" placeholder="搜索智能体名称或能力"/></div><div><button class="filter-button">全部状态<ChevronDown :size="14"/></button><button class="filter-button">全部模型<ChevronDown :size="14"/></button></div></header><div class="agent-type-grid"><article v-for="agent in filtered" :key="agent.id" class="agent-type-card" @click="router.push(`/admin/agent-types/${agent.id}`)"><header><span class="agent-type-avatar" :class="agent.color">{{agent.icon}}<i v-if="agent.status"></i></span><div><h3>{{agent.name}}</h3><code>{{agent.key}}</code></div><button class="icon-button" @click.stop><MoreHorizontal :size="17"/></button></header><p>{{agent.description}}</p><div class="agent-config-row"><span><BrainCircuit :size="14"/>{{agent.model}}</span><span><Wrench :size="14"/>{{agent.tools}} 工具</span><span><Sparkles :size="14"/>{{agent.skills}} Skills</span></div><div class="agent-performance"><div><small>成功率</small><strong>{{agent.success}}%</strong><i><em :style="{width:`${agent.success}%`}"></em></i></div><div><small>平均耗时</small><strong>{{agent.duration}}</strong></div><div><small>累计执行</small><strong>{{agent.runs}}</strong></div></div><footer><span :class="['agent-enabled',agent.status?'on':'off']"><i></i>{{agent.status?'已启用':'已停用'}}</span><button class="toggle-control" :class="{on:agent.status}" @click.stop="toggle(agent)"><i></i></button></footer></article></div></section></div></template>
