<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Bot, CheckCircle2, ChevronRight, Code2, FileCode2, FolderOpen, PackageCheck, Play, Plus, Puzzle, RefreshCcw, Search, ShieldCheck, Sparkles, Terminal, Wrench, X } from 'lucide-vue-next'
import { api, type SkillRecord } from '../../api/client'
import { useAppStore } from '../../stores/app'
import PageTitle from '../../components/PageTitle.vue'
import StatusBadge from '../../components/StatusBadge.vue'

const router=useRouter();const app=useAppStore();const skills=ref<SkillRecord[]>([]);const loading=ref(false);const search=ref('');const selected=ref<SkillRecord|null>(null);const executing=ref(false);const result=ref<Record<string,unknown>|null>(null)
const projects=ref<{id:string;name:string}[]>([]);const projectId=ref('')
const filtered=computed(()=>skills.value.filter(item=>`${item.displayName}${item.name}${item.description}${item.tags.join('')}`.toLowerCase().includes(search.value.toLowerCase())))
const agentLabels:Record<string,string>={'project-manager':'项目经理','requirement-analyst':'需求分析师','architect':'架构设计师','backend-developer':'后端开发','frontend-developer':'前端开发','code-reviewer':'代码审查','test-engineer':'测试工程师'}
async function load(){loading.value=true;try{skills.value=await api.skills();selected.value=selected.value?skills.value.find(s=>s.name===selected.value?.name)||skills.value[0]:skills.value[0];projects.value=await api.projects();if(!projectId.value&&projects.value.length)projectId.value=projects.value[0].id}catch(error){app.toast('Skill 加载失败',error instanceof Error?error.message:'请稍后重试')}finally{loading.value=false}}
async function reload(){try{skills.value=await api.reloadSkills();selected.value=skills.value[0];app.toast('Skill 已重新加载',`已校验并加载 ${skills.value.length} 个 Skills。`)}catch(error){app.toast('重载失败',error instanceof Error?error.message:'请检查 Skill Manifest')}}
function sampleInput(skill:SkillRecord){if(skill.name==='requirement-analysis')return{project_name:'演示项目',requirement:'构建员工培训系统，HR 发布课程，员工报名，需要权限、导出和审计日志。'};if(skill.name==='code-metrics')return{language:'python',code:'def hello(name):\n    if name:\n        return f"Hello {name}"\n    return "Hello"'};return{changed_modules:['课程服务','报名页面'],risk_level:'medium',existing_tests:[]}}
async function execute(){if(!selected.value)return;if(!projectId.value){app.toast('请先选择项目','Skill 执行需要关联一个项目记录运行结果。');return}executing.value=true;try{const run=await api.executeSkill(projectId.value,selected.value.name,sampleInput(selected.value),true);result.value=run.result;app.toast('Skill 执行完成',`${selected.value.displayName} 已在 ${run.backend} 沙箱运行。`)}catch(error){app.toast('执行失败',error instanceof Error?error.message:'请稍后重试')}finally{executing.value=false}}
onMounted(load)
</script>

<template><div class="content-width admin-page skills-admin-page"><PageTitle eyebrow="AGENT STUDIO" title="Skill 管理与装配" description="管理可复用能力包，并将 Skills 装配到专业智能体。"><button class="button secondary" @click="reload"><RefreshCcw :size="16"/>重新扫描目录</button><button class="button primary" @click="app.toast('创建 Skill','请在 backend/skills 下创建 skill.json、SKILL.md 和可选入口文件。')"><Plus :size="16"/>创建 Skill</button></PageTitle>
<div class="skill-run-project-bar"><span>沙箱试运行项目</span><select v-model="projectId"><option v-for="project in projects" :key="project.id" :value="project.id">{{project.name}}</option></select><small v-if="!projects.length">暂无可用项目，创建项目后可试运行 Skill</small></div>
<div class="admin-metrics"><article><span class="metric-icon indigo"><Puzzle :size="19"/></span><div><small>已加载 Skills</small><strong>{{skills.length}}</strong><em>全部通过 Manifest 校验</em></div></article><article><span class="metric-icon green"><PackageCheck :size="19"/></span><div><small>可执行</small><strong>{{skills.filter(s=>s.executable).length}}</strong><em>在隔离沙箱运行</em></div></article><article><span class="metric-icon blue"><Bot :size="19"/></span><div><small>已装配角色</small><strong>{{new Set(skills.flatMap(s=>s.agentTypes)).size}}</strong><em>按 AgentType 隔离加载</em></div></article><article><span class="metric-icon amber"><ShieldCheck :size="19"/></span><div><small>完整性校验</small><strong>SHA-256</strong><em>入口和说明文件校验</em></div></article></div>
<div class="skills-admin-layout"><section class="panel skills-catalog"><header class="table-toolbar"><div class="inline-search admin-search"><Search :size="15"/><input v-model="search" placeholder="搜索 Skill 名称、说明或标签"/></div><span>{{filtered.length}} 个能力包</span></header><div class="skills-catalog-list"><button v-for="skill in filtered" :key="skill.name" :class="{active:selected?.name===skill.name}" @click="selected=skill;result=null"><span><Puzzle :size="18"/></span><div><div><b>{{skill.displayName}}</b><StatusBadge status="completed" :label="skill.executable?'可执行':'Prompt'"/></div><code>{{skill.name}}@{{skill.version}}</code><p>{{skill.description}}</p><footer><em v-for="tag in skill.tags" :key="tag">#{{tag}}</em></footer></div><ChevronRight :size="16"/></button></div></section>
<section v-if="selected" class="panel skill-detail-admin"><header><div><span><Sparkles :size="20"/></span><div><h2>{{selected.displayName}}</h2><code>{{selected.name}}@{{selected.version}}</code></div></div><button class="button secondary" :disabled="!selected.executable||executing" @click="execute"><Play :size="14"/>沙箱试运行</button></header><div class="skill-detail-body"><section><h3>能力说明</h3><p>{{selected.description}}</p><div class="skill-file-meta"><span><FolderOpen :size="14"/>{{selected.path}}</span><span><FileCode2 :size="14"/>{{selected.entrypoint||'仅提示词'}}</span><span><ShieldCheck :size="14"/>{{selected.checksum.slice(0,12)}}…</span></div></section><section><h3>装配到智能体</h3><div class="skill-agent-assignment"><article v-for="agent in selected.agentTypes" :key="agent"><span class="agent-square">{{agent.slice(0,2).toUpperCase()}}</span><div><b>{{agentLabels[agent]||agent}}</b><small>{{agent}}</small></div><StatusBadge status="completed" label="已装配"/><button @click="router.push(`/admin/agent-types/${agent}?tab=capabilities`)">配置<ChevronRight :size="13"/></button></article><button class="assign-agent-button" @click="router.push('/admin/agent-types')"><Plus :size="14"/>装配到更多智能体</button></div></section><section><h3>Skill 指令</h3><pre>{{selected.instructions}}</pre></section><section v-if="result"><h3>最近试运行结果</h3><pre class="skill-result-output">{{JSON.stringify(result,null,2)}}</pre></section></div></section></div></div></template>
